detectors: 
  UtilityFunction:
    enabled: false
  TooManyStatements:
    enabled: false
  ControlParameter:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  NilCheck:
    enabled: false
