require: rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/SymbolProc: 
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
