require: rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
