source 'https://rubygems.org'

ruby '2.7.0'

group :development do
  gem 'reek', '~> 5.5'
  gem 'rubocop', '~> 0.78.0'
  gem 'rubocop-rspec', '~> 1.37'
end

group :test do
  gem 'rspec', '~> 3.9'
end
